---
- include_tasks: apt-key.yml

- name: Add Mesosphere repo
  apt_repository:
    repo: "{{ mesosphere_apt_repo }}"
    state: present
    update_cache: yes

- name: Install unzip package
  apt:
    pkg: unzip
    state: present
    install_recommends: no
    cache_valid_time: 3600

- name: Install Marathon package
  apt:
    pkg: "{{ marathon_apt_package }}"
    state: present
    install_recommends: no
    cache_valid_time: 3600
  notify: restart marathon
