---
- include_vars: "{{ ansible_os_family }}.yml"

- name: Check if upstart exists
  stat: path=/etc/init/
  register: etc_init_check

- name: Check if systemd exists
  stat: path=/bin/systemctl
  register: systemd_check

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: install wait script
  template:
    src: marathon-wait-for-listen.sh.j2
    dest: /usr/local/bin/marathon-wait-for-listen.sh
    mode: u=rwx,g=rx,o=rx
  tags:
    - marathon

- include: conf.yml

- name: configure marathon unit file
  sudo: yes
  replace:
    dest: /lib/systemd/system/marathon.service
    regexp: "=network.target"
    replace: '=mesos-master.service'
  when: systemd_check.stat.exists == True
  notify:
    - reload marathon
    - restart marathon
  tags:
    - marathon

- meta: flush_handlers

- name: Start Marathon service
  service: name=marathon state=restarted enabled=yes
