---
- include_vars: "{{ ansible_os_family }}.yml"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: install wait script
  template:
    src: marathon-wait-for-listen.sh.j2
    dest: /usr/local/bin/marathon-wait-for-listen.sh
    mode: u=rwx,g=rx,o=rx
  tags:
    - marathon

- include: conf.yml

- meta: flush_handlers

- include: haproxy.yml
  when: haproxy_script_location != ""

- name: Start Marathon service
  service: name=marathon state=restarted enabled=yes 
