---
- include_vars: "{{ ansible_os_family }}.yml"

- include: Debian.yml
  when: ansible_os_family == "Debian"

- include: RedHat.yml
  when: ansible_os_family == "RedHat"

- name: install wait script
  template:
    src: marathon-wait-for-listen.sh.j2
    dest: /usr/local/bin/marathon-wait-for-listen.sh
    mode: u=rwx,g=rx,o=rx
  tags:
    - marathon

- name: wait for zookeeper service to be registered
  wait_for:
    host: "{{ marathon_zk_dns }}"
    port: "{{ marathon_zk_port }}"
    delay: 10
    timeout: 300
    state: present
  tags:
    - marathon

- include: upstart-init.yml
  when: ansible_service_mgr != 'systemd'

- include: systemd-init.yml
  when: ansible_service_mgr == 'systemd'

- meta: flush_handlers

- name: Start Marathon service
  service: name=marathon state=restarted enabled=yes

- name: Ensure that Marathon has started
  service: name=marathon state=started
  tags: deploy
  register: marathon_running

- name: Validate that Marathon has started
  fail:
    msg: >
      Marathon has not started as expected, please check its current status or error messages
  when: marathon_running|changed
  tags: deploy
