---

- name: create marathon conf directory
  file:
    dest: /etc/marathon/conf
    state: directory
  tags:
    - marathon

- name: set key/value options
  when: item.value != ""
  copy:
    dest: /etc/marathon/conf/{{ item.key }}
    content: "{{ item.value }}"
  with_items:
    - key: zk
      value: "{{ marathon_zk_connect }}"
    - key: ssl_keystore_password
      value: "{{ marathon_keystore_password }}"
    - key: http_port
      value: "{{ marathon_port }}"
    - key: event_subscriber
      value: http_callback
    - key: hostname
      value: "{{ marathon_hostname }}"
    - key: mesos_role
      value: "{{ marathon_mesos_role }}"
    - key: mesos_authentication_principal
      value: "{{ marathon_principal }}"
  notify:
    - restart marathon
  tags:
    - marathon

# since the Mesosphere Marathon package configures itself with files
# in a directory, we need to clean up old options when they become
# unset.
- name: remove blank options
  when: item.value == ""
  file:
    dest: /etc/marathon/conf/{{ item.key }}
    state: absent
    mode: 0700
  with_items:
    - key: http_credentials
      value: "{{ marathon_http_credentials }}"
    - key: ssl_keystore_password
      value: "{{ marathon_keystore_password }}"
    - key: ssl_keystore_path
      value: "{{ marathon_keystore_path }}"
  notify:
    - restart marathon
  tags:
    - marathon

- name: Upstart environment variables
  lineinfile: dest=/etc/init/marathon.conf backup=yes state=present insertbefore='exec.*' line="env {{ item }}"
  with_items: '{{ marathon_env_vars }}'
  notify:
    - restart marathon
