---
- name: reload marathon
  become: yes
  command: systemctl daemon-reload
  notify:
    - wait for marathon to listen

- name: restart marathon
  service: name=marathon state=restarted
  notify:
    - wait for marathon to listen

- name: wait for marathon to listen
  command: /usr/local/bin/marathon-wait-for-listen.sh
